// build-levels.mjs — compile the hand-authored level folders into src/data/levels.json.
//
// Levels are authored as one JSON file per level under "GB - Levels/C<n> - <Name>/<n>-<m>.json".
// This script is the only thing that writes src/data/levels.json, which makes two guarantees:
//
//   1. THE FILENAME IS THE ID. Level ids are derived from the filename, never from the `id` field
//      inside the file. The editor defaults an id-less level to "custom-1" and that default has
//      round-tripped onto disk before, giving two different levels the same id — which would
//      silently break the unlock chain, the save keys and the HUD readout.
//   2. THE CHAPTER LIST LIVES HERE, not in the filesystem. Git cannot track an empty directory, so
//      a "coming soon" chapter with no levels yet would disappear on a fresh clone if the chapter
//      list were inferred from the folders.
//
// Usage:  node scripts/build-levels.mjs   (or `npm run levels:build`)
import { readdir, readFile, writeFile, copyFile, access } from 'node:fs/promises';
import { basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SRC_DIR = resolve(ROOT, 'GB - Levels');
const OUT = resolve(ROOT, 'src/data/levels.json');

// The shipping campaign. `short` is the level-select tab label (keep it under ~10 characters);
// `blurb` is the one-line teaser shown on a chapter's "coming soon" card.
const CHAPTERS = [
  {
    id: 1,
    name: 'Intro to Movement & Spikes',
    short: 'Spikes',
    mechanic: '4-way gravity shift + spikes',
    blurb: 'The only verb you get: choose which way is down, and live with the consequences.',
  },
  {
    id: 2,
    name: 'Sticky Pads & Trampolines',
    short: 'Bounce',
    mechanic: 'Sticky pads + trampolines',
    blurb: 'Pads that hold you until you flip away, and pads that fire you across the room.',
  },
  {
    id: 3,
    name: 'Lock & Keys',
    short: 'Keys',
    mechanic: 'Keys & doors',
    blurb: 'The exit is shut. Work out which detour opens it, and in what order.',
  },
  {
    id: 4,
    name: 'Breakable Blocks & Weight Zones',
    short: 'Fragile',
    mechanic: 'Breakable blocks + weight zones',
    blurb: 'Ground that shatters under a heavy ball, and the zones that make the ball heavy.',
  },
  {
    id: 5,
    name: 'Portals',
    short: 'Portals',
    mechanic: 'Momentum-preserving portals',
    blurb: 'Paired doorways that keep every bit of the speed you carry into them.',
  },
];

const SCHEMA_NOTE =
  'GENERATED by scripts/build-levels.mjs from the "GB - Levels" folders — edit the level files, not this. '
  + 'Levels are arrayed by chapter -> level. Border walls (24px) are auto-added by GameScene from `bounds` '
  + 'unless a level sets `border:false`, so `walls` only lists INTERIOR geometry. Coordinates are pixel '
  + 'centres. `par` = target shift count for a 3-star clear. A chapter with an empty `levels` array renders '
  + 'as "coming soon".';

const errors = [];
const warnings = [];

/** Folder for a chapter, or null when it has not been started yet (which is not an error). */
async function chapterDir(id) {
  const entries = await readdir(SRC_DIR, { withFileTypes: true });
  const match = entries.find((e) => e.isDirectory() && e.name[0] === 'C' && Number(e.name.slice(1).split('-')[0]) === id);
  return match ? resolve(SRC_DIR, match.name) : null;
}

async function loadChapter(meta) {
  const dir = await chapterDir(meta.id);
  if (!dir) {
    warnings.push(`chapter ${meta.id} (${meta.name}): no folder yet — shipping as "coming soon"`);
    return { ...meta, levels: [] };
  }

  const files = (await readdir(dir))
    .filter((f) => f.toLowerCase().endsWith('.json'))
    // Natural sort so 1-10 follows 1-9 rather than 1-1.
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  const levels = [];
  const seen = new Set();

  for (const file of files) {
    const label = `${basename(dir)}/${file}`;
    // .trim() because a filename has carried a stray space before the extension before now.
    const id = basename(file, '.json').trim();

    const parts = id.split('-');
    if (parts.length !== 2 || Number(parts[0]) !== meta.id || !/^[0-9]+$/.test(parts[1])) {
      errors.push(`${label}: filename must be "<chapter>-<n>.json" for chapter ${meta.id}`);
      continue;
    }
    if (seen.has(id)) {
      errors.push(`${label}: duplicate level id "${id}"`);
      continue;
    }
    seen.add(id);

    let level;
    try {
      level = JSON.parse(await readFile(resolve(dir, file), 'utf8'));
    } catch (err) {
      errors.push(`${label}: not valid JSON — ${err.message}`);
      continue;
    }

    if (!level.spawn || !level.goal) {
      errors.push(`${label}: missing ${!level.spawn ? 'spawn' : 'goal'}`);
      continue;
    }
    if (level.id !== id) {
      warnings.push(`${label}: id field said "${level.id}" — using the filename ("${id}")`);
    }
    if (!Array.isArray(level.solution)) {
      warnings.push(`${label}: no "solution" recorded — verify-folder.mjs will skip it`);
    }

    levels.push({ ...level, id });
  }

  // Level numbers should run 1..N with no holes, or the unlock chain has an invisible gap.
  const numbers = levels.map((l) => Number(l.id.split('-')[1])).sort((a, b) => a - b);
  numbers.forEach((n, i) => {
    if (n !== i + 1) errors.push(`chapter ${meta.id}: level numbers are not contiguous (saw ${n} at position ${i + 1})`);
  });

  return { ...meta, levels };
}

const chapters = [];
for (const meta of CHAPTERS) chapters.push(await loadChapter(meta));

for (const w of warnings) console.warn(`  warn  ${w}`);
if (errors.length) {
  for (const e of errors) console.error(`  ERROR ${e}`);
  console.error(`\n${errors.length} error(s) — levels.json NOT written.\n`);
  process.exit(1);
}

// Back up before overwriting: this file is the whole campaign.
await access(OUT).then(() => copyFile(OUT, `${OUT}.bak`)).catch(() => {});
await writeFile(OUT, `${JSON.stringify({ '$schema-note': SCHEMA_NOTE, chapters }, null, 2)}\n`);

const built = chapters.filter((c) => c.levels.length);
const total = chapters.reduce((n, c) => n + c.levels.length, 0);
console.log('\n  src/data/levels.json rebuilt');
for (const c of chapters) {
  const count = c.levels.length;
  console.log(`    ${c.id}. ${c.name.padEnd(34)} ${count ? `${String(count).padStart(2)} levels` : ' coming soon'}`);
}
console.log(`\n  ${built.length} chapters built, ${chapters.length - built.length} coming soon, `
  + `${total} levels, ${total * 3} stars available.\n`);
